# Generated by Django 5.2.1 on 2025-06-04 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobapplication_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
