# Generated by Django 5.2.1 on 2025-06-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobapplication_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
